name: CI

on:
  push:
    branches:
      - master

jobs:
     
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: setup create-elm-app scripts
      run: npm install create-elm-app 
    - name: build and test
      run: |
        node node_modules/.bin/elm-app build
        node node_modules/.bin/elm-app test
    
    - name: publish to github pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: build/
        GH_PAT: ${{ secrets.GITHUB_PAGES_PAT }}
